### PR TITLE
New React Context API

### LINKED ISSUE #20: The way context is done in React has changed
In future versions of react, a context provider is paired with a context consumer. https://reactjs.org/docs/legacy-context.html shows how context works in react 16 while later versions will use a context consumer. Will this module be broken in future versions of react?

### PR DESCRIPTION
**Pull request by adrianmcli**
Fixes #20

This PR adds a new DrizzleContext object that relies on the new [React Context API](https://reactjs.org/docs/context.html). It uses the [Render Prop pattern](https://reactjs.org/docs/render-props.html), which has become the new gold standard for sharing things between components in React.

We have also bumped React dependency to v16.4.2, but we retain the old API for compatibility.

Here's how it works...

# 1. Setup the Provider

```js
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

// Setup Drizzle
import { Drizzle, generateStore } from "drizzle";
import { DrizzleContext } from "drizzle-react";
import SimpleStorage from "./contracts/SimpleStorage.json";

const options = { contracts: [SimpleStorage] };
const drizzleStore = generateStore(options);
const drizzle = new Drizzle(options, drizzleStore);

// Pass in the drizzle instance into the provider
ReactDOM.render(
  <DrizzleContext.Provider drizzle={drizzle}>
    <App />
  </DrizzleContext.Provider>,
  document.getElementById("root")
);
```

# 2. Setup the Consumer

Then, in any child component of the app, we can access the `drizzle` instance as well as the `drizzleState`.

In our render tree, we use the `DrizzleContext.Consumer` component to get access to Drizzle. This component will call its function child with the following object:

```js
const drizzleContext = {
  drizzle,       // this is the drizzle instance (use this to call `cacheCall` and `cacheSend`)
  drizzleState,  // this is the entire Drizzle state, it will always be up-to-date
  initialized    // this boolean value will indicate when Drizzle is ready
}
```

Please see the following example:

```js
import React from "react";
import { DrizzleContext } from "drizzle-react";

export default () => (
  <DrizzleContext.Consumer>
    {drizzleContext => {
      const { drizzle, drizzleState, initialized } = drizzleContext;
  
      if (!initialized) {
        return "Loading...";
      }

      return (
        <MyDrizzleApp drizzle={drizzle} drizzleState={drizzleState} />
      );
    }}
  </DrizzleContext.Consumer>
)
```

# 3. Reference: `<MyDrizzleApp />`

For reference, here is an example of what `<MyDrizzleApp />` might look like:

```js
import React from "react";

export default class MyDrizzleApp extends React.Component {
  state = { dataKey: null };

  componentDidMount() {
    const { drizzle } = this.props;
    const contract = drizzle.contracts.SimpleStorage;

    // get and save the key for the variable we are interested in
    const dataKey = contract.methods["storedData"].cacheCall();
    this.setState({ dataKey });
  }

  render() {
    const { SimpleStorage } = this.props.drizzleState.contracts;
    const storedData = SimpleStorage.storedData[this.state.dataKey];
    return <p>My stored value: {storedData && storedData.value}</p>;
  }
}
```

### Caveat

The `drizzleState` will keep refreshing, if you don't want unnecessary re-renders, then you'll need to put in your own logic to compare the slice of state you are interested in. It's also advisable to use PureComponent wherever possible to mitigate this.

### CODE REVIEW

**Comment by kartojal** [comment]
Hi! Is it going to be merged? Currently i'm using this patch in my drizzle-box for the Consensys course. But don't know if this new API will be used in the future.

**Comment by adrianmcli** [comment]
@kartojal Going to have a meeting about this today, will get back to you soon.

**Comment by skylarweaver** [comment]
Seconded! Any update?

**Comment by DiscRiskandBisque** [comment]
@skylarweaver @kartojal Merging and releasing this later today!

**Pull request merged**
